# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: default

steps:
  - task: AzureContainerApps@1
    inputs:
      azureSubscription: 'YOUR-SERVICE-CONNECTION-NAME'  # Use correct service connection
      acrName: 'taoacr1224'  # ACR Name
      imageToDeploy: 'taoacr1224.azurecr.io/aspnetcorecontainer:latest'  # Ensure image is correct
      containerAppName: 'tao-app-1'  # Your Container App name
      resourceGroup: 'RG1'  # Ensure the Resource Group is correct
      location: 'Australia East'  # Ensure region is correct
      targetPort: '80'  # Match your app's configuration
      disableTelemetry: true  # Optional, disable telemetry if needed

  # Additional custom steps if needed
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'




